FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /code

COPY mcp-requirements.txt /code/mcp-requirements.txt

RUN pip install \
    --no-cache-dir \
    --upgrade \
    -r /code/mcp-requirements.txt

RUN adduser \
    --disabled-password \
    --gecos "" \
    mcpuser

COPY --chown=mcpuser:mcpuser \
    ./mcp_server \
    /code/mcp_server

USER mcpuser

EXPOSE 8001

CMD ["python", "-m", "mcp_server.server"]