import os
from typing import Any

import httpx
from mcp.server import MCPServer
from mcp.server.transport_security import TransportSecuritySettings
from starlette.requests import Request
from starlette.responses import JSONResponse, Response


API_BASE_URL = os.getenv(
    "API_BASE_URL",
    "http://api:8000",
).rstrip("/")

API_TIMEOUT_SECONDS = float(
    os.getenv("API_TIMEOUT_SECONDS", "180")
)


mcp = MCPServer(
    "QualityPilot AI",
    version="0.1.0",
    instructions=(
        "Utilise ces outils pour consulter les documents indexés "
        "et obtenir des réponses RAG sourcées."
    ),
)


async def call_api(
    method: str,
    path: str,
    json_body: dict[str, Any] | None = None,
) -> Any:
    try:
        async with httpx.AsyncClient(
            base_url=API_BASE_URL,
            timeout=API_TIMEOUT_SECONDS,
        ) as client:
            response = await client.request(
                method=method,
                url=path,
                json=json_body,
            )

            response.raise_for_status()

    except httpx.HTTPStatusError as exc:
        raise RuntimeError(
            "QualityPilot API returned an error: "
            f"{exc.response.status_code} {exc.response.text}"
        ) from exc

    except httpx.RequestError as exc:
        raise RuntimeError(
            f"QualityPilot API is unreachable: {exc}"
        ) from exc

    try:
        return response.json()

    except ValueError as exc:
        raise RuntimeError(
            "QualityPilot API returned invalid JSON"
        ) from exc


@mcp.tool()
async def list_documents() -> list[dict[str, Any]]:
    """
    List all documents currently indexed by QualityPilot AI.

    Returns document names, chunk counts and creation dates.
    """
    result = await call_api(
        method="GET",
        path="/documents",
    )

    if not isinstance(result, list):
        raise RuntimeError(
            "QualityPilot API returned an invalid document list"
        )

    return result


@mcp.tool()
async def ask_qualitypilot(
    question: str,
    top_k: int = 3,
) -> dict[str, Any]:
    """
    Ask QualityPilot AI a question about the indexed documents.

    Returns a grounded answer generated by the local LLM together
    with the document passages and similarity scores used as sources.
    """
    question = question.strip()

    if len(question) < 3:
        raise ValueError(
            "The question must contain at least 3 characters"
        )

    if not 1 <= top_k <= 10:
        raise ValueError(
            "top_k must be between 1 and 10"
        )

    result = await call_api(
        method="POST",
        path="/ask",
        json_body={
            "question": question,
            "top_k": top_k,
        },
    )

    if not isinstance(result, dict):
        raise RuntimeError(
            "QualityPilot API returned an invalid RAG answer"
        )

    return result


@mcp.custom_route("/health", methods=["GET"])
async def health(_: Request) -> Response:
    return JSONResponse(
        {
            "status": "ok",
            "service": "qualitypilot-mcp",
            "api_base_url": API_BASE_URL,
        }
    )


transport_security = TransportSecuritySettings(
    allowed_hosts=[
        "localhost",
        "localhost:*",
        "127.0.0.1",
        "127.0.0.1:*",
        "mcp",
        "mcp:*",
    ]
)


if __name__ == "__main__":
    mcp.run(
        transport="streamable-http",
        host="0.0.0.0",
        port=8001,
        streamable_http_path="/mcp",
        json_response=True,
        stateless_http=True,
        transport_security=transport_security,
    )